branches: [ master ]

workspace:
  base: /go
  path: src/github.com/GowerStreet/drone-lambda-plugin

slack: &slack
  image: plugins/slack
  webhook: "${SLACK_WEBHOOK}"
  secrets: [ slack_webhook ]
  username: Drone CI
  icon_url: https://pbs.twimg.com/profile_images/573911705505259520/rShq67tG_400x400.png

steps:
  build:
    image: golang:1.9
    environment:
      - CGO_ENABLED=0
    commands:
      - go get ./...
      - go build main.go

  publish-latest-image:
    image: plugins/docker
    build_args:
      - "TAG=1.0.${DRONE_BUILD_NUMBER}"
    repo: gowerstreet/drone-lambda-plugin
    secrets: [docker_username, docker_password]
    tags:
      - latest
      - "1.0.${DRONE_BUILD_NUMBER}"
